//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MostaStoreWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string SIMCard { get; set; }
        public string FrontCam { get; set; }
        public Nullable<int> BackCam { get; set; }
        public string Screen { get; set; }
        public Nullable<int> PhoneSize { get; set; }
        public Nullable<int> RAM { get; set; }
    }
}
